import Head from "next/head";
import { useContext } from "react";

import { AuthContext } from "../AuthContext";

export default function Home() {
  const { user } = useContext(AuthContext);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello!
      {JSON.stringify(user?.record?.username)}
    </div>
  );
}
